version: '3.7'

services:

  mongo-db:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  server:
    build: ProyectoEA_Backend
    image: backend
    ports:
      - '3000:3000'
    links:
      - mongo-db
    volumes:
      - mongo-data:/data/db
    networks:
      - proxy-tier

  client:
    build: ProyectoEA_Backoffice
    image: frontend
    ports:
      - '80:80'
    networks:
      - proxy-tier

networks:
  db-tier:
    driver: bridge
  proxy-tier:
    driver: bridge

volumes:
  mongo-data:
   driver: local